version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: e-commerce-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-123456}
      - POSTGRES_DB=${DB_DATABASE:-e-commerce}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - e-commerce-network

  redis:
    image: redis:latest
    container_name: e-commerce-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - e-commerce-network

volumes:
  postgres_data:
  redis_data:

networks:
  e-commerce-network:
    driver: bridge
